name: Deactivate Delinquent Stake

on:
  workflow_dispatch:
  schedule:
    - cron: '50 * * * *'

jobs:
  build:
    name: Deactivate Delinquent Stake
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - uses: pnpm/action-setup@v2
      name: Install pnpm
      with:
        version: 8
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install

    - name: Deactivate Delinquent Stake
      env:
        GH_TOKEN: ${{ github.token }}
        KEYPAIR_RAW: ${{ secrets.KEYPAIR }}
      run: |
        set -e

        echo "$KEYPAIR_RAW" > keypair.json

        mkdir -p logs
        FILE="./logs/$(date --iso-8601=s).log"

        export KEYPAIR=keypair.json
        node index.js |& tee "$FILE"

        if ! grep -q 'Total de-activated: 0$' "$FILE"; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add logs
          git commit -m "Added log file $FILE"
          git push
        fi
